const PLATFORMER_PACK = "/assets/KayKit_Platformer_Pack_1.0_SOURCE";
const PLATFORMER_GLTF = `${PLATFORMER_PACK}/Assets/gltf`;
const CHARACTER = "/assets/KayKit_Character_Animations_1.1";

export const PLATFORMER_COLORS = ["blue", "green", "red", "yellow"] as const;
export type PlatformerColor = (typeof PLATFORMER_COLORS)[number];

export const PLATFORMER_MODELS = [
  "arch",
  "arch_tall",
  "arch_wide",
  "ball",
  "barrier_1x1x1",
  "barrier_1x1x2",
  "barrier_1x1x4",
  "barrier_2x1x1",
  "barrier_2x1x2",
  "barrier_2x1x4",
  "barrier_3x1x1",
  "barrier_3x1x2",
  "barrier_3x1x4",
  "barrier_4x1x1",
  "barrier_4x1x2",
  "barrier_4x1x4",
  "bomb_A",
  "bomb_B",
  "bracing_large",
  "bracing_medium",
  "bracing_small",
  "button_base",
  "cannon_base",
  "chest",
  "chest_large",
  "cone",
  "conveyor_2x4x1",
  "conveyor_2x8x1",
  "conveyor_4x4x1",
  "conveyor_4x8x1",
  "diamond",
  "flag_A",
  "flag_B",
  "flag_C",
  "floor_net_2x2x1",
  "floor_net_4x4x1",
  "floor_spikes_trap_2x2x1",
  "floor_spikes_trap_4x4x1",
  "hammer",
  "hammer_large",
  "hammer_large_spikes",
  "hammer_spikes",
  "heart",
  "hoop",
  "hoop_angled",
  "lever_floor_base",
  "lever_wall_base_A",
  "lever_wall_base_B",
  "pipe_180_A",
  "pipe_180_B",
  "pipe_90_A",
  "pipe_90_B",
  "pipe_end",
  "pipe_straight_A",
  "pipe_straight_B",
  "platform_1x1x1",
  "platform_2x2x1",
  "platform_2x2x2",
  "platform_2x2x4",
  "platform_4x2x1",
  "platform_4x2x2",
  "platform_4x2x4",
  "platform_4x4x1",
  "platform_4x4x2",
  "platform_4x4x4",
  "platform_6x2x1",
  "platform_6x2x2",
  "platform_6x2x4",
  "platform_6x6x1",
  "platform_6x6x2",
  "platform_6x6x4",
  "platform_arrow_2x2x1",
  "platform_arrow_4x4x1",
  "platform_decorative_1x1x1",
  "platform_decorative_2x2x2",
  "platform_hole_6x6x1",
  "platform_slope_2x2x2",
  "platform_slope_2x4x4",
  "platform_slope_2x6x4",
  "platform_slope_4x2x2",
  "platform_slope_4x4x4",
  "platform_slope_4x6x4",
  "platform_slope_6x2x2",
  "platform_slope_6x4x4",
  "platform_slope_6x6x4",
  "power",
  "railing_corner_double",
  "railing_corner_padded",
  "railing_corner_single",
  "railing_straight_double",
  "railing_straight_padded",
  "railing_straight_single",
  "safetynet_2x2x1",
  "safetynet_4x2x1",
  "safetynet_6x2x1",
  "saw_trap",
  "saw_trap_double",
  "saw_trap_long",
  "signage_arrow_stand",
  "signage_arrow_wall",
  "signage_arrows_left",
  "signage_arrows_right",
  "spikeblock_double_horizontal",
  "spikeblock_double_vertical",
  "spikeblock_down",
  "spikeblock_left",
  "spikeblock_omni",
  "spikeblock_quad",
  "spikeblock_right",
  "spikeblock_up",
  "spring_pad",
  "star",
  "swiper",
  "swiper_double",
  "swiper_double_long",
  "swiper_long",
  "swiper_quad",
  "swiper_quad_long",
] as const;

export const PLATFORMER_NEUTRAL_MODELS = [
  "ball",
  "barrier_1x1x1",
  "barrier_1x1x2",
  "barrier_1x1x4",
  "barrier_2x1x1",
  "barrier_2x1x2",
  "barrier_2x1x4",
  "barrier_3x1x1",
  "barrier_3x1x2",
  "barrier_3x1x4",
  "barrier_4x1x1",
  "barrier_4x1x2",
  "barrier_4x1x4",
  "bomb",
  "cannon_bullet",
  "chain_full",
  "chain_link",
  "chain_link_end_bottom",
  "chain_link_end_top",
  "cone",
  "floor_spikes_2x2x1",
  "floor_spikes_4x4x1",
  "floor_spikes_curved_4x2x2",
  "floor_wood_1x1",
  "floor_wood_2x2",
  "floor_wood_2x6",
  "floor_wood_4x4",
  "hammerblock",
  "hammerblock_spikes",
  "pillar_1x1x1",
  "pillar_1x1x2",
  "pillar_1x1x4",
  "pillar_1x1x8",
  "pillar_2x2x2",
  "pillar_2x2x4",
  "pillar_2x2x8",
  "platform_wood_1x1x1",
  "sawblade",
  "sign",
  "signage_arrows_left",
  "signage_arrows_right",
  "signage_finish",
  "signage_finish_wide",
  "spikeball",
  "spikeball_hanger",
  "spikeroller_horizontal",
  "spikeroller_vertical",
  "spring",
  "structure_A",
  "structure_B",
  "structure_C",
  "strut_horizontal",
  "strut_vertical",
] as const;

export const CHARACTER_RIG_NAMES = {
  large: "Rig_Large",
  medium: "Rig_Medium",
} as const;

export const CHARACTER_ANIMATIONS = {
  large: {
    combat_melee: "CombatMelee",
    general: "General",
    movement_advanced: "MovementAdvanced",
    movement_basic: "MovementBasic",
    simulation: "Simulation",
    special: "Special",
  },
  medium: {
    combat_melee: "CombatMelee",
    combat_ranged: "CombatRanged",
    general: "General",
    movement_advanced: "MovementAdvanced",
    movement_basic: "MovementBasic",
    simulation: "Simulation",
    special: "Special",
    tools: "Tools",
  },
} as const;

export const CHARACTER_MANNEQUINS = {
  large: "Mannequin_Large",
  medium: "Mannequin_Medium",
} as const;

export type PlatformerModel = (typeof PLATFORMER_MODELS)[number];
export type PlatformerNeutralModel = (typeof PLATFORMER_NEUTRAL_MODELS)[number];
export type CharacterRigSize = keyof typeof CHARACTER_RIG_NAMES;
export type CharacterAnimation<TSize extends CharacterRigSize = CharacterRigSize> =
  TSize extends CharacterRigSize ? keyof (typeof CHARACTER_ANIMATIONS)[TSize] : never;
export type CharacterMannequinSize = keyof typeof CHARACTER_MANNEQUINS;

export const platformerAsset = (color: PlatformerColor, model: PlatformerModel) =>
  `${PLATFORMER_GLTF}/${color}/${model}_${color}.gltf`;

export const platformerNeutralAsset = (model: PlatformerNeutralModel) => `${PLATFORMER_GLTF}/neutral/${model}.gltf`;

export const characterAnimationAsset = <TSize extends CharacterRigSize>(
  size: TSize,
  animation: CharacterAnimation<TSize>,
) => {
  const rigName = CHARACTER_RIG_NAMES[size];
  const fileName = CHARACTER_ANIMATIONS[size][animation];
  return `${CHARACTER}/Animations/gltf/${rigName}/${rigName}_${fileName}.glb`;
};

export const characterMannequinAsset = (size: CharacterMannequinSize) =>
  `${CHARACTER}/Mannequin Character/characters/${CHARACTER_MANNEQUINS[size]}.glb`;
