const PLATFORMER = "/assets/KayKit_Platformer_Pack_1.0_SOURCE/Assets/gltf";
const CHARACTER = "/assets/KayKit_Character_Animations_1.1";

export const ASSETS = {
  platform_yellow: `${PLATFORMER}/yellow/platform_6x6x4_yellow.gltf`,
  platform_blue: `${PLATFORMER}/blue/platform_6x6x4_blue.gltf`,
  platform_red: `${PLATFORMER}/red/platform_6x6x4_red.gltf`,
  barrier_tall: `${PLATFORMER}/red/barrier_4x1x4_red.gltf`,
  barrier_low: `${PLATFORMER}/red/barrier_4x1x2_red.gltf`,
  barrier_tall_blue: `${PLATFORMER}/blue/barrier_4x1x4_blue.gltf`,
  barrier_low_blue: `${PLATFORMER}/blue/barrier_4x1x2_blue.gltf`,
  conveyor_4x8x1_blue: `${PLATFORMER}/blue/conveyor_4x8x1_blue.gltf`,
  conveyor_4x8x1_red: `${PLATFORMER}/red/conveyor_4x8x1_red.gltf`,
  conveyor_4x4x1_blue: `${PLATFORMER}/blue/conveyor_4x4x1_blue.gltf`,
  conveyor_4x4x1_red: `${PLATFORMER}/red/conveyor_4x4x1_red.gltf`,
  platform_slope_4x6x4_blue: `${PLATFORMER}/blue/platform_slope_4x6x4_blue.gltf`,
  platform_slope_4x6x4_red: `${PLATFORMER}/red/platform_slope_4x6x4_red.gltf`,
  flag_blue: `${PLATFORMER}/blue/flag_A_blue.gltf`,
  flag_red: `${PLATFORMER}/red/flag_A_red.gltf`,
  arch_wide_blue: `${PLATFORMER}/blue/arch_wide_blue.gltf`,
  arch_wide_red: `${PLATFORMER}/red/arch_wide_red.gltf`,
  safetynet_6x2x1_blue: `${PLATFORMER}/blue/safetynet_6x2x1_blue.gltf`,
  safetynet_6x2x1_red: `${PLATFORMER}/red/safetynet_6x2x1_red.gltf`,
  pipe_straight_blue: `${PLATFORMER}/blue/pipe_straight_A_blue.gltf`,
  pipe_straight_red: `${PLATFORMER}/red/pipe_straight_A_red.gltf`,
  ball: `${PLATFORMER}/neutral/ball.gltf`,
  mannequin: `${CHARACTER}/Mannequin Character/characters/Mannequin_Medium.glb`,
  rig_general: `${CHARACTER}/Animations/gltf/Rig_Medium/Rig_Medium_General.glb`,
  rig_movement: `${CHARACTER}/Animations/gltf/Rig_Medium/Rig_Medium_MovementBasic.glb`,
} as const;
